---
driver:
  name: vagrant
  synced_folders:
    - ["../", "/vagrant"]

provisioner:
  name: chef_zero
  chef_omnibus_url: file:///vagrant/install_chef.sh

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[aws-iam::default]
  - name: create_certificate
    run_list:
      - recipe[aws-iam::create_certificate]
  - name: delete_certificate
    run_list:
      - recipe[aws-iam::delete_certificate]
